openapi: 3.0.3
info:
  version: 0.0.0
  title: Pinazu Core API
  description: |
    Pinazu Core is a microservices-based platform for orchestrating and managing AI Generative Application workflows. 
    
    The API provides endpoints for:
    - **Agent Management**: Configure and manage AI agents with support for Anthropic Claude, OpenAI, Google Gemini, and AWS Bedrock
    - **Workflow Orchestration**: Create and execute complex AI workflows with the Flows service
    - **Task Management**: Assign, track, and execute tasks across distributed systems
    - **Real-time Communication**: WebSocket endpoint at `/v1/ws` for live agent interactions
    - **Tool Integration**: Register and manage external tools for agent capabilities
    - **User & Thread Management**: Handle user authentication and conversation threading
    
    The platform uses NATS for inter-service messaging, PostgreSQL for persistence, and OpenTelemetry for observability.
    All services support both REST API and real-time WebSocket communication patterns.
  termsOfService: https://swagger.io/terms/
  contact:
    email: pinazu@kalliopedata.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://pinazu.sandbox.kalliopedata.io
    description: Sandbox server
tags:
  - name: agents
    description: Operations about AI agents
  - name: flows
    description: Operations about AI workflows
  - name: threads
    description: Operations about conversation threads
  - name: messages
    description: Operations about messages in threads
  - name: permissions
    description: Operations about permissions for OPA policies
  - name: users
    description: Operations about users
  - name: roles
    description: Operations about roles
  - name: tools
    description: Operations about tools, MCP and external services
  - name: mock
    description: Mock operations for testing purpose only